---
version: "3.6"
services:
  app:
    build:
      context: .
      target: app

  shell:
    build:
      context: .
      target: shell
    command:
    - /bin/sleep
    - "30758400"
    environment:
      CONFIG: devvalue
      SECRET:
    volumes:
    - .:/app
