---
version: '3.6'
services:
  shell:
    build:
      dockerfile: Dockerfile
    command: [/bin/sleep, "86400"]
    ports:
      - "8000:8000"
    volumes:
    - .:/app
    - ./tmp/home:/home/appuser
