---
version: '3.6'
services:
  shell:
    build:
      network: host
      context: .
    command: ["ruby", "-e", "sleep 86400"]
    ports:
    - 4000:4000
    volumes:
    - .:/app
    - ./_tmp/home:/home/appuser
