---
version: '3.6'
services:
  shell:
    build:
      dockerfile: Dockerfile
    command: [/bin/sleep, "86400"]
    ports:
      - "8000:8000"
    volumes:
    - $PWD:/app
    - $PWD/tmp/home/.bash_history:/home/appuser/.bash_history
    - $HOME/.gitconfig:/home/appuser/.gitconfig
    - $HOME/.ssh:/home/appuser/.ssh
