#!/bin/bash
# usage: ./Projectfile [command]

#
# develop
#

images () {
  docker compose build --parallel
}

up () {
  docker compose up --detach shell
}

shell () {
  touch tmp/home/.bash_history
  up && docker compose exec shell /bin/bash -l
}

rootshell () {
  up && docker compose exec -u root shell /bin/bash -l
}

down () {
  docker compose stop
}

clean () {
  docker compose rm -s -f -v
}

#
# helpers
#

run () {
  (sleep 3.5; open http://localhost:8000) &
  docker compose run --service-ports shell ./bin/run
}

#
# utility
#
set -e

list () {
  compgen -A function
}

if list | grep -qFx -- "${1:-}"
then "$@"; exit $?
else
  printf "unknown command: %s\n" "${1:-}" >&2
  exit 1
fi
