#!/bin/bash
# usage: ./Projectfile [command]

#
# develop
#

images () {
  docker-compose build --compress --parallel
}

up () {
  docker-compose up --detach shell
}

shell () {
  up && docker-compose exec shell /bin/bash -l
}

down () {
  docker-compose stop
}

clean () {
  docker-compose rm -s -f -v
}

start () {
  down && docker-compose run --rm --service-ports shell /app/Projectfile run
}

#
# helpers
#

log () {
  printf "[%s] %s %s - %s\n" "$(date +%Y-%m-%dT%H-%M-%S%z)" "$1" "$(basename "$0")" "$2" >&2
}

run () {
  bundle exec jekyll serve --host=0.0.0.0 --watch
}

update () {
  find {series,data} -name '*.yml' |
  while read yaml_file
  do
    log INFO "update $yaml_file"
    ./_bin/yaml2json "$yaml_file" > "${yaml_file%.yml}.json"
  done
}

#
# utility  
#

list () {
  compgen -A function
}

if list | grep -qFx -- "${1:-}"
then "$@"
else
  printf "unknown command: %s\n" "${1:-}" >&2
  exit 1
fi
