#!/bin/bash
# usage: ./Stackfile [command]

#
# develop
#

clean () {
	docker-compose down --remove-orphans --rmi all
}

images () {
	docker-compose build --compress --parallel
}

shell () {
	docker-compose run --rm --service-ports shell /bin/bash
}

start () {
	docker-compose run --rm --service-ports shell /app/Stackfile run
}

run () {
	bundle exec jekyll serve --host=0.0.0.0 --watch
}

#
# utility
#

list () {
	compgen -A function 2>/dev/null
}

if list | grep -qFx "$1"
then "$@"
else
	if [ -z "$1" ]
	then printf "no command specified (try 'list')\n" >&2
	else printf "unknown command: %s\n" "$1" >&2
	fi
	exit 1
fi
