---
apiVersion: v1
kind: Namespace
metadata:
  name: namespace5
---
apiVersion: v1
kind: Pod
metadata:
  name: timepod5
  namespace: namespace5
spec:
  containers:
  - name: app
    image: artifactory.pinnacol.com:4001/pinnacol/deployer-debian9-ruby2.6
    command:
    - /usr/local/bin/deployer_exec
    - env
    volumeMounts:
    - name: config-app
      mountPath: /etc/config/container
    - name: secret-app
      mountPath: /etc/secret/container
  volumes:
  - name: config-app
    configMap:
      name: timepod5
  - name: secret-app
    secret:
      secretName: timepod5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: timepod5
  namespace: namespace5
data:
  CONFIG: timepod5-config
---
apiVersion: v1
kind: Secret
metadata:
  name: timepod5
  namespace: namespace5
data:
  SECRET: dGltZXBvZDUtc2VjcmV0Cg== # "timepod5-secret"
