---
apiVersion: v1
kind: Pod
metadata:
  name: timepod4a
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: debian:stretch-slim
    command:
    - /bin/sh
    - -c
    - 'date -u "$FORMAT"'
    env:
    - name: FORMAT
      valueFrom:
        secretKeyRef:
          name: arbitrary-name
          key: arbitrary_key
---
apiVersion: v1
kind: Secret
metadata:
  name: arbitrary-name
data:
  arbitrary_key: KyVZLSVtLSVkOiVIOiVNOiVTWiAodGltZXBvZDRhKQo= # "+%Y-%m-%d:%H:%M:%SZ (timepod4a)"
