---
apiVersion: v1
kind: Pod
metadata:
  name: timepod4b
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: debian:stretch-slim
    command:
    - /bin/sh
    - -c
    - 'date -u "$(cat /etc/secret/container/FORMAT)"'
    volumeMounts:
    - name: secret-app
      mountPath: /etc/secret/container
  volumes:
  - name: secret-app
    secret:
      secretName: timepod4b
---
apiVersion: v1
kind: Secret
metadata:
  name: timepod4b
data:
  FORMAT: KyVZLSVtLSVkOiVIOiVNOiVTWiAodGltZXBvZDRiKQo= # "+%Y-%m-%d:%H:%M:%SZ (timepod4b)"
