---
apiVersion: v1
kind: Pod
metadata:
  name: timepod4c
spec:
  containers:
  - name: app
    image: alpine
    command:
    - /usr/local/bin/deployer_exec
    - /bin/sh
    - -c
    - 'date -u "$FORMAT"'
    volumeMounts:
    - name: container
      mountPath: /etc/config/container
  volumes:
    - name: container
      secret:
        secretName: timepod4c
---
apiVersion: v1
kind: Secret
metadata:
  name: timepod4c
data:
  FORMAT: KyVZLSVtLSVkOiVIOiVNOiVTWiAodGltZXBvZDRjKQo= # "+%Y-%m-%d:%H:%M:%SZ (timepod4c)"
