---
apiVersion: v1
kind: Pod
metadata:
  name: timepod3c
spec:
  containers:
  - name: app
    image: artifactory.pinnacol.com:4001/pinnacol/deployer-debian9-ruby2.6
    command:
    - /usr/local/bin/deployer_exec
    - /bin/sh
    - -c
    - 'date -u "$FORMAT"'
    volumeMounts:
    - name: config-app
      mountPath: /etc/config/container
  volumes:
  - name: config-app
    configMap:
      name: timepod3c
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: timepod3c
data:
  FORMAT: "+%Y-%m-%d:%H:%M:%SZ (timepod3c)"
