---
apiVersion: v1
kind: Pod
metadata:
  name: timepod4c
spec:
  containers:
  - name: app
    image: artifactory.pinnacol.com:4001/pinnacol/deployer-debian9-ruby2.6
    command:
    - /usr/local/bin/deployer_exec
    - /bin/sh
    - -c
    - 'date -u "$FORMAT"'
    volumeMounts:
    - name: secret-app
      mountPath: /etc/config/container
  volumes:
  - name: secret-app
    secret:
      secretName: timepod4c
---
apiVersion: v1
kind: Secret
metadata:
  name: timepod4c
data:
  FORMAT: KyVZLSVtLSVkOiVIOiVNOiVTWiAodGltZXBvZDRjKQo= # "+%Y-%m-%d:%H:%M:%SZ (timepod4c)"
