---
apiVersion: v1
kind: Pod
metadata:
  name: timepod6-one-c
  labels:
    group: one
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: debian:stretch-slim
    command:
    - date
    - -u
    - "+%Y-%m-%d:%H:%M:%SZ (timepod6-one-c)"
